### ISSUE TITLE
Sign up with Twitter

### ISSUE THREAD

**Issue by TeriPastorino** [TeriPastorino/KnoWater#1]

**Comment by TeriPastorino** [comment]
@levicole I think this one is done

**Comment by TeriPastorino** [comment]
let me know if there is anything else you would expect to see on this one

**Comment by levicole** [comment]
Where is our SessionsController? It seems to be missing.

**Comment by TeriPastorino** [comment]
yes it was, oh my 

should be there now 

----- Original Message -----
